name: Install > Build > Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Using Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install
      run: npm ci
    - name: Build
      run: npm run build:production
    - name: Install Test Dependencies
      run: cd test; npm ci;
    - name: Test
      run: npm test
